---
title: "neural network prep"
author: "MP"
date: "22 7 2017"
output: html_document
---

```{r}
library(dplyr)
load("/home/Vera_Weidmann/Supermarket/00_Data/boing_test.rda")

label_user <- boing_test %>% group_by(user_id) %>% filter(order_number==max(order_number)) %>% select(nextbasket=vector2)
label <- boing_test %>% group_by(user_id) %>% filter(order_number==max(order_number)) %>% ungroup() %>% select(nextbasket=vector2)

train <- boing_test %>% group_by(user_id) %>% filter(order_number!=max(order_number)) %>% summarise(baskets=list(vector1))

test <- boing_test %>% group_by(user_id) %>% summarise(baskets=list(vector1))

vh(boing_test)
vh(train)
vh(test)
vh(label_user)

head(label_user) # last basekt Y
head(label)      # last basket Y
head(train)      # traindata X -> baskets - last basket
head(test)       # testdata -> all baskets

label_user$nextbasket <- as.character(label_user$nextbasket)
label$nextbasket <- as.character(label$nextbasket)
train$baskets <- as.character(train$baskets)
test$baskets <- as.character(test$baskets)
vh(boing_test)
boing_test$vector1 <- as.character(boing_test$vector1)
boing_test$vector2 <- as.character(boing_test$vector2)
class(boing_test$basket)

#vh(test)

write.csv(boing_test, file = "boing_test.csv" )
write.csv(label_user, file="nn_label_user.csv")
write.csv(label, file="nn_label.csv")
write.csv(train, file="nn_train.csv")
write.csv(test, file="nn_test.csv")

```

```{r}
X2 <- boing_test %>% group_by(user_id) %>% filter(order_number!=max(order_number)) %>% select (user_id, order_number, basket) 
Y2 <- boing_test %>% group_by(user_id) %>% filter(order_number==max(order_number)) %>% ungroup()  %>% select (user_id, order_number, basket)

head(X2)
head(Y2)

library(splitstackshape)
X2 <- splitstackshape::cSplit(X2,splitCols = "basket", sep = " ",direction = "wide")
Y2 <- splitstackshape::cSplit(Y2,splitCols = "basket", sep = " ",direction = "wide")
vh(X2)
vh(Y2)

write.csv(X2, file = "nn_X.csv" )
write.csv(Y2, file="nn_Y.csv")

```


```{r}
head(op)
```


```{r}
vh(orders_products)

op <- orders_products %>% select (user_id, order_number, product_id, order_dow, order_hour_of_day, days_since_prior_order, add_to_cart_order, reordered) %>% arrange(user_id, order_number, add_to_cart_order)

vh(op)
```

Split into X and Y:

```{r}

#testorders <- orders %>% filter(eval_set=="test") %>% select(user_id,order_id)
#testusers <- testorders[,1] #75000 users

X <- orders_products %>% group_by(user_id) %>% filter(order_number!=max(order_number) & user_id %in% testusers) %>% ungroup()
Y <- orders_products %>% group_by(user_id) %>% filter(order_number==max(order_number) & user_id %in% testusers) %>% ungroup()

dim(X)
vh(Y)

write.csv(X, file = "X_train.csv" )
write.csv(Y, file = "Y_train.csv" )
```

```{r}
head(orders_products,150)
orders_products <- orders_products %>% filter(eval_set == "prior" & user_id %in% testusers)


X3 <- orders_products %>% group_by(user_id) %>% filter(order_number!=max(order_number)) %>% select (user_id, order_number, product_id) 
Y3 <- orders_products %>% group_by(user_id) %>% filter(order_number==max(order_number)) %>% ungroup() %>% select (user_id, order_number, product_id)
vh(X3)
vh(Y3)
write.csv(X3, "Input_RNN.csv")
write.csv(Y3, "Output_RNN.csv")

```

