---
title: "minimarkov"
author: "MP"
date: "13 7 2017"
output: html_document
---

```{r}
library(dplyr)
library(markovchain)
library(purrr)
library(tidyr)
load("/home/Vera_Weidmann/Supermarket/00_Data/boing_test.rda")
load("/home/Max_Philipp/bigdata/cutofflookup.rda")
lookup <- lookup %>% group_by(user_id) %>% mutate(cutoff=max(round((user_reorder_ratio+(1-user_reorder_ratio)/2)*user_average_basket),1))
last_orders <- boing_test%>% group_by(user_id) %>% filter(order_number==max(order_number)) %>% select(user_id,vector2) %>% ungroup()
rm(boing_test)
gc()
load("/home/Vera_Weidmann/Supermarket/00_Data/par_longdata_test.rda")
colnames(longdata_test) <- c("A","B","user_id")

mmc <- longdata_test %>% filter(user_id=="36855" | user_id=="35220") %>% group_by(user_id) %>% nest(-user_id)
rm(longdata_test)
gc()
mmc <- mmc %>% mutate(user_id=as.numeric(as.character(user_id)))

create_minimarkov <- function(data=data){as.data.frame(markovchainFit(data)$estimate@transitionMatrix)}

#secure_trans <- function(x){as.numeric(as.character(x))}


mmc <- mmc  %>% 
  group_by(user_id) %>% 
  mutate(markov= map(data,~ create_minimarkov(.))) %>% 
  select(user_id,markov) %>%
  ungroup()
mmc <- mmc %>%
  left_join(last_orders, by="user_id")


```

```{r}
library(dplyr)
library(markovchain)
library(purrr)
library(tidyr)
load("/home/Vera_Weidmann/Supermarket/00_Data/boing_test.rda")
load("/home/Max_Philipp/bigdata/cutofflookup.rda")
lookup <- lookup %>% group_by(user_id) %>% mutate(cutoff=max(round((user_reorder_ratio+(1-user_reorder_ratio)/2)*user_average_basket),1))
last_orders <- boing_test%>% group_by(user_id) %>% filter(order_number==max(order_number)) %>% select(user_id,vector2) %>% ungroup()
rm(boing_test)
gc()
load("/home/Max_Philipp/bigdataproject/00_R_scrits_bash/fittedmarkovs.rda")

mmc <- mmc %>%
  left_join(lookup, by="user_id")

get_preds <- function(data=markov,basket=vector2){
  data[basket,] %>% colMeans() %>% sort(decreasing=TRUE)
}

oneitemusers <-mmc %>% filter(user_average_basket==1 & user_reorder_ratio==1)

mmc <- mmc %>% filter(!user_id %in% oneitemusers$user_id)

y <- get_preds(mmc$markov[[1]],mmc$vector2[[1]])
y= y[y>0]
x <- as.data.frame(cbind(user_id=mmc$user_id[1],
                         order_id=mmc$order_id[1], 
                         product_id=names(y),
                         reordered=as.numeric(y)),stringsAsFactors=FALSE)
preds <- x

for(i in 2:nrow(mmc)){
  y <- get_preds(mmc$markov[[i]],mmc$vector2[[i]])
  y= y[y>0]
  x <- as.data.frame(cbind(user_id=mmc$user_id[i],
                           order_id=mmc$order_id[i], 
                           product_id=names(y),
                           reordered=as.numeric(y)),stringsAsFactors=FALSE)
  preds <- bind_rows(preds,x)
  print(i)
}


#save(preds, file="markovchainpreds.rda")
```

```{r}
load("/home/Max_Philipp/bigdataproject/00_R_scrits_bash/markovchainpreds.rda")
nauser <- preds %>% filter(is.na(product_id))
```

```{r}
get_preds_all <- function(data=markov,basket=vector2){
  data %>% colMeans() %>% sort(decreasing=TRUE)
}


nammc <- mmc %>% filter(user_id %in% nauser$user_id)

y <- get_preds_all(nammc$markov[[1]],nammc$vector2[[1]])
y= y[y>0]
x <- as.data.frame(cbind(user_id=nammc$user_id[1],
                         order_id=nammc$order_id[1], 
                         product_id=names(y),
                         reordered=as.numeric(y)),stringsAsFactors=FALSE)
preds_na <- x

for(i in 2:nrow(nammc)){
  y <- get_preds_all(nammc$markov[[i]],nammc$vector2[[i]])
  y= y[y>0]
  x <- as.data.frame(cbind(user_id=nammc$user_id[i],
                           order_id=nammc$order_id[i], 
                           product_id=names(y),
                           reordered=as.numeric(y)),stringsAsFactors=FALSE)
  preds_na <- bind_rows(preds_na,x)
  print(i)
}

```


```{r}


submission <- preds %>% 
  mutate(order_id=as.numeric(order_id)) %>%
  left_join(lookup[,c(5,3)],by="order_id") %>% 
  filter(!is.na(product_id)) %>%
  group_by(order_id) %>% 
    mutate(index=row_number()) %>% 
  filter(index<=user_average_basket) %>%
  summarise(products =paste(product_id, collapse = " ")) %>% 
  ungroup() %>% 
  select(order_id,products)

oneitemsub <- oneitemusers %>% mutate(vector2=as.character(vector2)) %>% select(order_id,products=vector2)

nasub <- preds_na %>%
  mutate(order_id=as.numeric(order_id)) %>%
  left_join(lookup[,c(5,3)],by="order_id") %>% 
  group_by(order_id) %>% 
    mutate(index=row_number()) %>% 
  filter(index<=user_average_basket) %>%
  summarise(products =paste(product_id, collapse = " ")) %>% 
  ungroup() %>% 
  select(order_id,products)

submission_all <- bind_rows(submission, oneitemsub, nasub) %>% arrange(order_id)

write.csv(submission_all, file = "sub_minimarkov_2307.csv", row.names = F)
```
